// <auto-generated />
using System;
using CRUD_asp.netMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_asp.netMVC.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD_asp.netMVC.Models.AddToCart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Manufactures", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Samsung"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Sony"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Dell"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Asus"
                        });
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.OrderDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("orderID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("orderID");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Orders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<double>("totalPrice")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Payment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("paidAmount")
                        .HasColumnType("float");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("manuID")
                        .HasColumnType("int");

                    b.Property<int>("typeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("manuID");

                    b.HasIndex("typeID");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Điện thoại Apple với camera 48MP, chip A16 Bionic.",
                            Name = "iPhone 14 Pro",
                            PicturePath = "iphone14pro.jpg",
                            Price = 999.0,
                            manuID = 1,
                            typeID = 1
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flagship mạnh mẽ nhất của Samsung, màn hình 120Hz.",
                            Name = "Samsung Galaxy S23 Ultra",
                            PicturePath = "s23ultra.jpg",
                            Price = 1199.0,
                            manuID = 2,
                            typeID = 1
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tai nghe chống ồn tốt nhất, chất âm cao cấp.",
                            Name = "Sony WH-1000XM5",
                            PicturePath = "sonyxm5.jpg",
                            Price = 349.0,
                            manuID = 3,
                            typeID = 4
                        },
                        new
                        {
                            ID = 4,
                            Created = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Laptop Apple chạy chip M2, hiệu năng mạnh mẽ.",
                            Name = "MacBook Pro M2 13 inch",
                            PicturePath = "macbookpro13.jpg",
                            Price = 1299.0,
                            manuID = 1,
                            typeID = 2
                        },
                        new
                        {
                            ID = 5,
                            Created = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Laptop gaming mỏng nhẹ, card RTX 4060.",
                            Name = "Asus ROG Zephyrus G14",
                            PicturePath = "zephyrusg14.jpg",
                            Price = 1599.0,
                            manuID = 5,
                            typeID = 2
                        },
                        new
                        {
                            ID = 6,
                            Created = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tablet Apple với chip M1, thiết kế mỏng nhẹ.",
                            Name = "iPad Air 5th Gen",
                            PicturePath = "ipadair5.jpg",
                            Price = 599.0,
                            manuID = 1,
                            typeID = 3
                        },
                        new
                        {
                            ID = 7,
                            Created = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tablet cao cấp với màn hình AMOLED 120Hz.",
                            Name = "Samsung Galaxy Tab S8",
                            PicturePath = "tabs8.jpg",
                            Price = 699.0,
                            manuID = 2,
                            typeID = 3
                        },
                        new
                        {
                            ID = 8,
                            Created = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đồng hồ thông minh của Apple, theo dõi sức khỏe.",
                            Name = "Apple Watch Series 9",
                            PicturePath = "applewatch9.jpg",
                            Price = 399.0,
                            manuID = 1,
                            typeID = 5
                        });
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Prototype", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Prototypes", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Smartphone"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Tablet"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Headphones"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Smartwatch"
                        });
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Reviews", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Roles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("roleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("roleID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.AddToCart", b =>
                {
                    b.HasOne("CRUD_asp.netMVC.Models.Products", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUD_asp.netMVC.Models.Users", "Users")
                        .WithMany("Carts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.OrderDetail", b =>
                {
                    b.HasOne("CRUD_asp.netMVC.Models.Products", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUD_asp.netMVC.Models.Orders", "Orders")
                        .WithMany("OrderDetail")
                        .HasForeignKey("orderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Orders", b =>
                {
                    b.HasOne("CRUD_asp.netMVC.Models.Users", "Users")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Payment", b =>
                {
                    b.HasOne("CRUD_asp.netMVC.Models.Orders", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("CRUD_asp.netMVC.Models.Payment", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Products", b =>
                {
                    b.HasOne("CRUD_asp.netMVC.Models.Manufacturer", "Manufactures")
                        .WithMany("products")
                        .HasForeignKey("manuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUD_asp.netMVC.Models.Prototype", "Types")
                        .WithMany("products")
                        .HasForeignKey("typeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufactures");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Reviews", b =>
                {
                    b.HasOne("CRUD_asp.netMVC.Models.Products", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUD_asp.netMVC.Models.Users", "Users")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Users", b =>
                {
                    b.HasOne("CRUD_asp.netMVC.Models.Roles", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Manufacturer", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Orders", b =>
                {
                    b.Navigation("OrderDetail");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Products", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Prototype", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRUD_asp.netMVC.Models.Users", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
